"""
interview_prep.py
-----------------
Role-specific interview question bank + Groq AI personalized question generator.

Static Q&A bank: 10 questions per role (technical + behavioral).
Groq AI: generates custom questions based on the user's resume context.
"""

from groq import Groq
from typing import List, Dict, Any, Optional
import os
import json

# Load from environment — never hardcode secrets
GROQ_API_KEY = os.getenv("GROQ_API_KEY", "")
MODEL = "llama-3.1-8b-instant"

# ---------------------------------------------------------------------------
# Static Q&A bank keyed by job id
# ---------------------------------------------------------------------------
INTERVIEW_BANK: Dict[str, List[Dict]] = {
    "data_scientist": [
        {"q": "Explain the bias-variance tradeoff.", "difficulty": "Medium", "type": "Technical", "hint": "Correct Answer: Option B. High bias = underfitting, high variance = overfitting. Balance via regularization, cross-validation.", "options": ['Using a deprecated pattern that negatively impacts performance.', 'High bias = underfitting, high variance = overfitting. Balance via regularization, cross-validation.', 'A completely unrelated method often confused by beginners.', 'A standard approach that incorrectly handles edge cases.'], "correct_index": 1},
        {"q": "How would you handle a highly imbalanced dataset?", "difficulty": "Medium", "type": "Technical", "hint": "Correct Answer: Option A. SMOTE, class weights, oversampling, undersampling, or changing evaluation metric to F1/AUC.", "options": ['SMOTE, class weights, oversampling, undersampling, or changing evaluation metric to F1/AUC.', 'Using a deprecated pattern that negatively impacts performance.', 'A completely unrelated method often confused by beginners.', 'A standard approach that incorrectly handles edge cases.'], "correct_index": 0},
        {"q": "Walk me through a complete machine learning project lifecycle.", "difficulty": "Easy", "type": "Technical", "hint": "Correct Answer: Option D. Problem definition → data collection → EDA → feature engineering → modeling → evaluation → deployment → monitoring.", "options": ['A standard approach that incorrectly handles edge cases.', 'A completely unrelated method often confused by beginners.', 'Using a deprecated pattern that negatively impacts performance.', 'Problem definition → data collection → EDA → feature engineering → modeling → evaluation → deployment → monitoring.'], "correct_index": 3},
        {"q": "What is the difference between L1 and L2 regularization?", "difficulty": "Medium", "type": "Technical", "hint": "Correct Answer: Option A. L1 = Lasso, produces sparse models. L2 = Ridge, shrinks all weights. Elastic Net combines both.", "options": ['L1 = Lasso, produces sparse models. L2 = Ridge, shrinks all weights. Elastic Net combines both.', 'A standard approach that incorrectly handles edge cases.', 'Using a deprecated pattern that negatively impacts performance.', 'A completely unrelated method often confused by beginners.'], "correct_index": 0},
        {"q": "How do you detect and handle outliers in a dataset?", "difficulty": "Easy", "type": "Technical", "hint": "Correct Answer: Option B. Z-score, IQR method, box plots. Handle by removal, transformation (log), or capping.", "options": ['A completely unrelated method often confused by beginners.', 'Z-score, IQR method, box plots. Handle by removal, transformation (log), or capping.', 'A standard approach that incorrectly handles edge cases.', 'Using a deprecated pattern that negatively impacts performance.'], "correct_index": 1},
        {"q": "Explain how gradient descent works.", "difficulty": "Medium", "type": "Technical", "hint": "Correct Answer: Option B. Iteratively adjust weights in direction of negative gradient of loss. Learning rate controls step size.", "options": ['A standard approach that incorrectly handles edge cases.', 'Iteratively adjust weights in direction of negative gradient of loss. Learning rate controls step size.', 'Using a deprecated pattern that negatively impacts performance.', 'A completely unrelated method often confused by beginners.'], "correct_index": 1},
        {"q": "What metrics would you use for a fraud detection model?", "difficulty": "Hard", "type": "Technical", "hint": "Correct Answer: Option C. Precision-Recall curve, AUC-ROC, F1. Accuracy is misleading on imbalanced data.", "options": ['A standard approach that incorrectly handles edge cases.', 'A completely unrelated method often confused by beginners.', 'Precision-Recall curve, AUC-ROC, F1. Accuracy is misleading on imbalanced data.', 'Using a deprecated pattern that negatively impacts performance.'], "correct_index": 2},
        {"q": "Tell me about a time you found a surprising insight in data.", "difficulty": "Easy", "type": "Behavioral", "hint": "Correct Answer: Option A. Use STAR: Situation, Task, Action, Result. Emphasize impact on business decision.", "options": ['Use STAR: Situation, Task, Action, Result. Emphasize impact on business decision.', 'Using a deprecated pattern that negatively impacts performance.', 'A completely unrelated method often confused by beginners.', 'A standard approach that incorrectly handles edge cases.'], "correct_index": 0},
        {"q": "How do you communicate complex analysis to non-technical stakeholders?", "difficulty": "Easy", "type": "Behavioral", "hint": "Correct Answer: Option B. Focus on business impact, use visualizations, avoid jargon, tell a story with data.", "options": ['Using a deprecated pattern that negatively impacts performance.', 'Focus on business impact, use visualizations, avoid jargon, tell a story with data.', 'A standard approach that incorrectly handles edge cases.', 'A completely unrelated method often confused by beginners.'], "correct_index": 1},
        {"q": "What's the difference between supervised, unsupervised, and reinforcement learning?", "difficulty": "Easy", "type": "Technical", "hint": "Correct Answer: Option C. Supervised = labeled data, unsupervised = patterns without labels, RL = reward-based agent learning.", "options": ['A standard approach that incorrectly handles edge cases.', 'Using a deprecated pattern that negatively impacts performance.', 'Supervised = labeled data, unsupervised = patterns without labels, RL = reward-based agent learning.', 'A completely unrelated method often confused by beginners.'], "correct_index": 2},
    ],
    "data_analyst": [
        {"q": "Write a SQL query to find the second highest salary.", "difficulty": "Medium", "type": "Technical", "hint": "Correct Answer: Option D. Use DENSE_RANK() or subquery with NOT IN (max salary).", "options": ['Using a deprecated pattern that negatively impacts performance.', 'A completely unrelated method often confused by beginners.', 'A standard approach that incorrectly handles edge cases.', 'Use DENSE_RANK() or subquery with NOT IN (max salary).'], "correct_index": 3},
        {"q": "What is the difference between INNER JOIN and LEFT JOIN?", "difficulty": "Easy", "type": "Technical", "hint": "Correct Answer: Option B. INNER = matching rows only. LEFT = all rows from left table + matching from right.", "options": ['A completely unrelated method often confused by beginners.', 'INNER = matching rows only. LEFT = all rows from left table + matching from right.', 'A standard approach that incorrectly handles edge cases.', 'Using a deprecated pattern that negatively impacts performance.'], "correct_index": 1},
        {"q": "How do you handle NULL values in SQL?", "difficulty": "Easy", "type": "Technical", "hint": "Correct Answer: Option A. IS NULL / IS NOT NULL, COALESCE(), ISNULL(), NVL(). Never use = NULL.", "options": ['IS NULL / IS NOT NULL, COALESCE(), ISNULL(), NVL(). Never use = NULL.', 'Using a deprecated pattern that negatively impacts performance.', 'A completely unrelated method often confused by beginners.', 'A standard approach that incorrectly handles edge cases.'], "correct_index": 0},
        {"q": "How would you build a dashboard to track monthly revenue?", "difficulty": "Medium", "type": "Technical", "hint": "Correct Answer: Option D. Identify KPIs, aggregate data by month, choose Tableau/Power BI, add trend lines and filters.", "options": ['Using a deprecated pattern that negatively impacts performance.', 'A standard approach that incorrectly handles edge cases.', 'A completely unrelated method often confused by beginners.', 'Identify KPIs, aggregate data by month, choose Tableau/Power BI, add trend lines and filters.'], "correct_index": 3},
        {"q": "Explain the difference between variance and standard deviation.", "difficulty": "Easy", "type": "Technical", "hint": "Correct Answer: Option C. Variance = average squared deviation. SD = square root of variance. SD is in original units.", "options": ['A standard approach that incorrectly handles edge cases.', 'Using a deprecated pattern that negatively impacts performance.', 'Variance = average squared deviation. SD = square root of variance. SD is in original units.', 'A completely unrelated method often confused by beginners.'], "correct_index": 2},
        {"q": "What is a Pivot Table and when would you use it?", "difficulty": "Easy", "type": "Technical", "hint": "Correct Answer: Option A. Summarize large datasets by grouping and aggregating. Used for cross-tabulation analysis.", "options": ['Summarize large datasets by grouping and aggregating. Used for cross-tabulation analysis.', 'A completely unrelated method often confused by beginners.', 'A standard approach that incorrectly handles edge cases.', 'Using a deprecated pattern that negatively impacts performance.'], "correct_index": 0},
        {"q": "How do you validate the quality of a dataset before analysis?", "difficulty": "Medium", "type": "Technical", "hint": "Correct Answer: Option C. Check for nulls, duplicates, outliers, data types, distribution, referential integrity.", "options": ['A completely unrelated method often confused by beginners.', 'Using a deprecated pattern that negatively impacts performance.', 'Check for nulls, duplicates, outliers, data types, distribution, referential integrity.', 'A standard approach that incorrectly handles edge cases.'], "correct_index": 2},
        {"q": "Describe a time you used data to influence a business decision.", "difficulty": "Easy", "type": "Behavioral", "hint": "Correct Answer: Option A. STAR format. Quantify the result — 'increased revenue by 15%' is more powerful than vague statements.", "options": ["STAR format. Quantify the result — 'increased revenue by 15%' is more powerful than vague statements.", 'A standard approach that incorrectly handles edge cases.', 'A completely unrelated method often confused by beginners.', 'Using a deprecated pattern that negatively impacts performance.'], "correct_index": 0},
        {"q": "What is A/B testing and how would you set one up?", "difficulty": "Medium", "type": "Technical", "hint": "Correct Answer: Option C. Control vs treatment group. Define hypothesis, sample size (power analysis), duration, metric, p-value threshold.", "options": ['A completely unrelated method often confused by beginners.', 'A standard approach that incorrectly handles edge cases.', 'Control vs treatment group. Define hypothesis, sample size (power analysis), duration, metric, p-value threshold.', 'Using a deprecated pattern that negatively impacts performance.'], "correct_index": 2},
        {"q": "How do you prioritize when you have multiple urgent analysis requests?", "difficulty": "Easy", "type": "Behavioral", "hint": "Correct Answer: Option B. Communicate with stakeholders, assess business impact and deadline, break into subtasks, provide ETAs.", "options": ['A completely unrelated method often confused by beginners.', 'Communicate with stakeholders, assess business impact and deadline, break into subtasks, provide ETAs.', 'A standard approach that incorrectly handles edge cases.', 'Using a deprecated pattern that negatively impacts performance.'], "correct_index": 1},
    ],
    "ai_engineer": [
        {"q": "Explain how a Transformer architecture works.", "difficulty": "Hard", "type": "Technical", "hint": "Correct Answer: Option D. Self-attention mechanism, multi-head attention, positional encoding, encoder-decoder structure.", "options": ['A completely unrelated method often confused by beginners.', 'A standard approach that incorrectly handles edge cases.', 'Using a deprecated pattern that negatively impacts performance.', 'Self-attention mechanism, multi-head attention, positional encoding, encoder-decoder structure.'], "correct_index": 3},
        {"q": "What is the difference between fine-tuning and prompt engineering?", "difficulty": "Medium", "type": "Technical", "hint": "Correct Answer: Option C. Fine-tuning updates model weights on specific data. Prompt engineering guides without changing weights.", "options": ['A standard approach that incorrectly handles edge cases.', 'Using a deprecated pattern that negatively impacts performance.', 'Fine-tuning updates model weights on specific data. Prompt engineering guides without changing weights.', 'A completely unrelated method often confused by beginners.'], "correct_index": 2},
        {"q": "How would you deploy an ML model to production?", "difficulty": "Medium", "type": "Technical", "hint": "Correct Answer: Option D. Docker containerize → REST API (FastAPI) → monitor with MLflow/Prometheus → CI/CD pipeline.", "options": ['A standard approach that incorrectly handles edge cases.', 'Using a deprecated pattern that negatively impacts performance.', 'A completely unrelated method often confused by beginners.', 'Docker containerize → REST API (FastAPI) → monitor with MLflow/Prometheus → CI/CD pipeline.'], "correct_index": 3},
        {"q": "What are embedding vectors and why are they used in NLP?", "difficulty": "Medium", "type": "Technical", "hint": "Correct Answer: Option B. Dense numerical representations of semantic meaning. Similar concepts have similar vectors.", "options": ['A completely unrelated method often confused by beginners.', 'Dense numerical representations of semantic meaning. Similar concepts have similar vectors.', 'Using a deprecated pattern that negatively impacts performance.', 'A standard approach that incorrectly handles edge cases.'], "correct_index": 1},
        {"q": "Explain RAG (Retrieval Augmented Generation).", "difficulty": "Hard", "type": "Technical", "hint": "Correct Answer: Option C. Retrieve relevant docs from vector DB → augment LLM prompt → generate grounded response.", "options": ['A standard approach that incorrectly handles edge cases.', 'Using a deprecated pattern that negatively impacts performance.', 'Retrieve relevant docs from vector DB → augment LLM prompt → generate grounded response.', 'A completely unrelated method often confused by beginners.'], "correct_index": 2},
        {"q": "How do you evaluate a language model's performance?", "difficulty": "Medium", "type": "Technical", "hint": "Correct Answer: Option B. Perplexity, BLEU/ROUGE for generation, human eval, task-specific benchmarks (GLUE, SuperGLUE).", "options": ['A completely unrelated method often confused by beginners.', 'Perplexity, BLEU/ROUGE for generation, human eval, task-specific benchmarks (GLUE, SuperGLUE).', 'Using a deprecated pattern that negatively impacts performance.', 'A standard approach that incorrectly handles edge cases.'], "correct_index": 1},
        {"q": "What is model quantization and why is it used?", "difficulty": "Hard", "type": "Technical", "hint": "Correct Answer: Option B. Reduce model weight precision (FP32→INT8) to decrease memory/compute. Slight accuracy trade-off.", "options": ['A standard approach that incorrectly handles edge cases.', 'Reduce model weight precision (FP32→INT8) to decrease memory/compute. Slight accuracy trade-off.', 'Using a deprecated pattern that negatively impacts performance.', 'A completely unrelated method often confused by beginners.'], "correct_index": 1},
        {"q": "Describe a challenging AI system you built and the problems you solved.", "difficulty": "Medium", "type": "Behavioral", "hint": "Correct Answer: Option D. STAR format. Focus on technical challenges, trade-offs made, and measurable outcomes.", "options": ['A standard approach that incorrectly handles edge cases.', 'A completely unrelated method often confused by beginners.', 'Using a deprecated pattern that negatively impacts performance.', 'STAR format. Focus on technical challenges, trade-offs made, and measurable outcomes.'], "correct_index": 3},
        {"q": "How do you handle hallucinations in LLM-based applications?", "difficulty": "Hard", "type": "Technical", "hint": "Correct Answer: Option B. RAG for grounding, output validation, confidence scoring, human-in-the-loop, constrained decoding.", "options": ['A standard approach that incorrectly handles edge cases.', 'RAG for grounding, output validation, confidence scoring, human-in-the-loop, constrained decoding.', 'A completely unrelated method often confused by beginners.', 'Using a deprecated pattern that negatively impacts performance.'], "correct_index": 1},
        {"q": "What is MLOps and why is it important?", "difficulty": "Medium", "type": "Technical", "hint": "Correct Answer: Option D. Practices for ML lifecycle in production: versioning, CI/CD for models, monitoring, retraining triggers.", "options": ['A standard approach that incorrectly handles edge cases.', 'A completely unrelated method often confused by beginners.', 'Using a deprecated pattern that negatively impacts performance.', 'Practices for ML lifecycle in production: versioning, CI/CD for models, monitoring, retraining triggers.'], "correct_index": 3},
    ],
    "ml_engineer": [
        {"q": "What is feature engineering and give 3 examples.", "difficulty": "Medium", "type": "Technical", "hint": "Correct Answer: Option A. Creating new features from raw data: binning, polynomial features, interaction terms, TF-IDF.", "options": ['Creating new features from raw data: binning, polynomial features, interaction terms, TF-IDF.', 'A standard approach that incorrectly handles edge cases.', 'A completely unrelated method often confused by beginners.', 'Using a deprecated pattern that negatively impacts performance.'], "correct_index": 0},
        {"q": "Explain cross-validation and why it's important.", "difficulty": "Easy", "type": "Technical", "hint": "Correct Answer: Option C. K-fold: split data into k parts, train on k-1 test on 1. Reduces overfitting, better generalization estimate.", "options": ['A completely unrelated method often confused by beginners.', 'A standard approach that incorrectly handles edge cases.', 'K-fold: split data into k parts, train on k-1 test on 1. Reduces overfitting, better generalization estimate.', 'Using a deprecated pattern that negatively impacts performance.'], "correct_index": 2},
        {"q": "What is the ROC curve and AUC score?", "difficulty": "Medium", "type": "Technical", "hint": "Correct Answer: Option D. ROC plots TPR vs FPR at each threshold. AUC = area under curve. 0.5 = random, 1.0 = perfect.", "options": ['A standard approach that incorrectly handles edge cases.', 'Using a deprecated pattern that negatively impacts performance.', 'A completely unrelated method often confused by beginners.', 'ROC plots TPR vs FPR at each threshold. AUC = area under curve. 0.5 = random, 1.0 = perfect.'], "correct_index": 3},
        {"q": "How would you build a recommendation system?", "difficulty": "Hard", "type": "Technical", "hint": "Correct Answer: Option D. Collaborative filtering (user-item matrix), content-based (item features), or hybrid. Matrix factorization or deep learning.", "options": ['A standard approach that incorrectly handles edge cases.', 'Using a deprecated pattern that negatively impacts performance.', 'A completely unrelated method often confused by beginners.', 'Collaborative filtering (user-item matrix), content-based (item features), or hybrid. Matrix factorization or deep learning.'], "correct_index": 3},
        {"q": "Explain how Random Forest works.", "difficulty": "Medium", "type": "Technical", "hint": "Correct Answer: Option C. Ensemble of decision trees trained on bootstrapped samples with feature subsets. Vote for final prediction.", "options": ['Using a deprecated pattern that negatively impacts performance.', 'A completely unrelated method often confused by beginners.', 'Ensemble of decision trees trained on bootstrapped samples with feature subsets. Vote for final prediction.', 'A standard approach that incorrectly handles edge cases.'], "correct_index": 2},
        {"q": "What is hyperparameter tuning and what methods do you use?", "difficulty": "Medium", "type": "Technical", "hint": "Correct Answer: Option A. Grid search, random search, Bayesian optimization, HyperOpt, Optuna. Define search space + metric.", "options": ['Grid search, random search, Bayesian optimization, HyperOpt, Optuna. Define search space + metric.', 'A completely unrelated method often confused by beginners.', 'Using a deprecated pattern that negatively impacts performance.', 'A standard approach that incorrectly handles edge cases.'], "correct_index": 0},
        {"q": "How do you detect model drift in production?", "difficulty": "Hard", "type": "Technical", "hint": "Correct Answer: Option A. Monitor input distribution shift (PSI, KS-test), output distribution, and prediction quality metrics over time.", "options": ['Monitor input distribution shift (PSI, KS-test), output distribution, and prediction quality metrics over time.', 'Using a deprecated pattern that negatively impacts performance.', 'A completely unrelated method often confused by beginners.', 'A standard approach that incorrectly handles edge cases.'], "correct_index": 0},
        {"q": "Walk me through your approach for a new ML problem.", "difficulty": "Easy", "type": "Behavioral", "hint": "Correct Answer: Option C. Understand business goal → define success metric → explore data → baseline → iterate → evaluate → deploy.", "options": ['A completely unrelated method often confused by beginners.', 'Using a deprecated pattern that negatively impacts performance.', 'Understand business goal → define success metric → explore data → baseline → iterate → evaluate → deploy.', 'A standard approach that incorrectly handles edge cases.'], "correct_index": 2},
        {"q": "Explain the difference between batch and online learning.", "difficulty": "Medium", "type": "Technical", "hint": "Correct Answer: Option D. Batch = train on full dataset periodically. Online = update incrementally with each new data point.", "options": ['A completely unrelated method often confused by beginners.', 'A standard approach that incorrectly handles edge cases.', 'Using a deprecated pattern that negatively impacts performance.', 'Batch = train on full dataset periodically. Online = update incrementally with each new data point.'], "correct_index": 3},
        {"q": "How do you ensure reproducibility in ML experiments?", "difficulty": "Medium", "type": "Technical", "hint": "Correct Answer: Option D. Seed random numbers, version data + code + models (DVC, MLflow), containerize environment.", "options": ['A standard approach that incorrectly handles edge cases.', 'Using a deprecated pattern that negatively impacts performance.', 'A completely unrelated method often confused by beginners.', 'Seed random numbers, version data + code + models (DVC, MLflow), containerize environment.'], "correct_index": 3},
    ],
    "frontend_developer": [
        {"q": "What is the Virtual DOM and how does React use it?", "difficulty": "Medium", "type": "Technical", "hint": "Correct Answer: Option B. Lightweight JS object tree. React compares (diffs) virtual vs real DOM, updates only changed nodes.", "options": ['A standard approach that incorrectly handles edge cases.', 'Lightweight JS object tree. React compares (diffs) virtual vs real DOM, updates only changed nodes.', 'A completely unrelated method often confused by beginners.', 'Using a deprecated pattern that negatively impacts performance.'], "correct_index": 1},
        {"q": "Explain the difference between useEffect and useLayoutEffect.", "difficulty": "Medium", "type": "Technical", "hint": "Correct Answer: Option B. useEffect runs after paint. useLayoutEffect runs synchronously after DOM mutations, before paint.", "options": ['Using a deprecated pattern that negatively impacts performance.', 'useEffect runs after paint. useLayoutEffect runs synchronously after DOM mutations, before paint.', 'A completely unrelated method often confused by beginners.', 'A standard approach that incorrectly handles edge cases.'], "correct_index": 1},
        {"q": "What are some ways to optimize React application performance?", "difficulty": "Hard", "type": "Technical", "hint": "Correct Answer: Option B. Memoization (React.memo, useMemo, useCallback), code splitting, lazy loading, virtualization, bundle analysis.", "options": ['A standard approach that incorrectly handles edge cases.', 'Memoization (React.memo, useMemo, useCallback), code splitting, lazy loading, virtualization, bundle analysis.', 'Using a deprecated pattern that negatively impacts performance.', 'A completely unrelated method often confused by beginners.'], "correct_index": 1},
        {"q": "Explain how CSS Flexbox works.", "difficulty": "Easy", "type": "Technical", "hint": "Correct Answer: Option D. Main axis vs cross axis. justify-content/align-items for alignment. flex-grow/shrink/basis for sizing.", "options": ['A standard approach that incorrectly handles edge cases.', 'A completely unrelated method often confused by beginners.', 'Using a deprecated pattern that negatively impacts performance.', 'Main axis vs cross axis. justify-content/align-items for alignment. flex-grow/shrink/basis for sizing.'], "correct_index": 3},
        {"q": "What is the difference between sessionStorage and localStorage?", "difficulty": "Easy", "type": "Technical", "hint": "Correct Answer: Option A. localStorage persists until cleared. sessionStorage clears on tab close. Both ~5MB, synchronous, string only.", "options": ['localStorage persists until cleared. sessionStorage clears on tab close. Both ~5MB, synchronous, string only.', 'A completely unrelated method often confused by beginners.', 'A standard approach that incorrectly handles edge cases.', 'Using a deprecated pattern that negatively impacts performance.'], "correct_index": 0},
        {"q": "What is a closure in JavaScript?", "difficulty": "Medium", "type": "Technical", "hint": "Correct Answer: Option A. Function that remembers its outer scope after outer function has returned. Used in module pattern, callbacks, IIFE.", "options": ['Function that remembers its outer scope after outer function has returned. Used in module pattern, callbacks, IIFE.', 'Using a deprecated pattern that negatively impacts performance.', 'A standard approach that incorrectly handles edge cases.', 'A completely unrelated method often confused by beginners.'], "correct_index": 0},
        {"q": "How do you handle accessibility in web applications?", "difficulty": "Medium", "type": "Technical", "hint": "Correct Answer: Option D. ARIA attributes, semantic HTML, keyboard navigation, color contrast, alt text, screen reader testing.", "options": ['A standard approach that incorrectly handles edge cases.', 'Using a deprecated pattern that negatively impacts performance.', 'A completely unrelated method often confused by beginners.', 'ARIA attributes, semantic HTML, keyboard navigation, color contrast, alt text, screen reader testing.'], "correct_index": 3},
        {"q": "Describe a complex UI component you built and the challenges.", "difficulty": "Medium", "type": "Behavioral", "hint": "Correct Answer: Option D. STAR format. Focus on performance, reusability, state management, and edge cases handled.", "options": ['A standard approach that incorrectly handles edge cases.', 'A completely unrelated method often confused by beginners.', 'Using a deprecated pattern that negatively impacts performance.', 'STAR format. Focus on performance, reusability, state management, and edge cases handled.'], "correct_index": 3},
        {"q": "What is CSS specificity and how is it calculated?", "difficulty": "Easy", "type": "Technical", "hint": "Correct Answer: Option C. Inline(1000) > ID(100) > Class(10) > Element(1). Higher specificity wins, same specificity → last in file.", "options": ['A completely unrelated method often confused by beginners.', 'A standard approach that incorrectly handles edge cases.', 'Inline(1000) > ID(100) > Class(10) > Element(1). Higher specificity wins, same specificity → last in file.', 'Using a deprecated pattern that negatively impacts performance.'], "correct_index": 2},
        {"q": "How do you approach cross-browser compatibility?", "difficulty": "Medium", "type": "Technical", "hint": "Correct Answer: Option D. CSS resets, feature detection (Modernizr), progressive enhancement, polyfills, browser dev tools.", "options": ['A completely unrelated method often confused by beginners.', 'A standard approach that incorrectly handles edge cases.', 'Using a deprecated pattern that negatively impacts performance.', 'CSS resets, feature detection (Modernizr), progressive enhancement, polyfills, browser dev tools.'], "correct_index": 3},
    ],
    "backend_developer": [
        {"q": "What is the difference between SQL and NoSQL databases?", "difficulty": "Easy", "type": "Technical", "hint": "Correct Answer: Option D. SQL = structured tables, ACID, vertical scaling. NoSQL = flexible schema, BASE, horizontal scaling.", "options": ['A completely unrelated method often confused by beginners.', 'A standard approach that incorrectly handles edge cases.', 'Using a deprecated pattern that negatively impacts performance.', 'SQL = structured tables, ACID, vertical scaling. NoSQL = flexible schema, BASE, horizontal scaling.'], "correct_index": 3},
        {"q": "Explain REST API design principles.", "difficulty": "Easy", "type": "Technical", "hint": "Correct Answer: Option B. Stateless, uniform interface, resource-based URLs, HTTP methods (GET/POST/PUT/DELETE), JSON responses.", "options": ['Using a deprecated pattern that negatively impacts performance.', 'Stateless, uniform interface, resource-based URLs, HTTP methods (GET/POST/PUT/DELETE), JSON responses.', 'A standard approach that incorrectly handles edge cases.', 'A completely unrelated method often confused by beginners.'], "correct_index": 1},
        {"q": "How would you scale a backend to handle 10 million requests/day?", "difficulty": "Hard", "type": "Technical", "hint": "Correct Answer: Option A. Load balancing, caching (Redis), database indexing, connection pooling, CDN, microservices, auto-scaling.", "options": ['Load balancing, caching (Redis), database indexing, connection pooling, CDN, microservices, auto-scaling.', 'A standard approach that incorrectly handles edge cases.', 'A completely unrelated method often confused by beginners.', 'Using a deprecated pattern that negatively impacts performance.'], "correct_index": 0},
        {"q": "What is database indexing and when should you use it?", "difficulty": "Medium", "type": "Technical", "hint": "Correct Answer: Option A. Data structure that speeds up queries. Use on frequently queried/joined columns. Avoid on rarely queried or write-heavy columns.", "options": ['Data structure that speeds up queries. Use on frequently queried/joined columns. Avoid on rarely queried or write-heavy columns.', 'A standard approach that incorrectly handles edge cases.', 'Using a deprecated pattern that negatively impacts performance.', 'A completely unrelated method often confused by beginners.'], "correct_index": 0},
        {"q": "Explain the difference between authentication and authorization.", "difficulty": "Easy", "type": "Technical", "hint": "Correct Answer: Option A. Auth = verify identity (who are you?). Authz = verify permissions (what can you do?). JWT handles both.", "options": ['Auth = verify identity (who are you?). Authz = verify permissions (what can you do?). JWT handles both.', 'Using a deprecated pattern that negatively impacts performance.', 'A completely unrelated method often confused by beginners.', 'A standard approach that incorrectly handles edge cases.'], "correct_index": 0},
        {"q": "What is a race condition and how do you prevent it?", "difficulty": "Hard", "type": "Technical", "hint": "Correct Answer: Option D. Multiple threads access shared resource unpredictably. Prevent with locks, mutexes, atomic operations, transactions.", "options": ['A completely unrelated method often confused by beginners.', 'Using a deprecated pattern that negatively impacts performance.', 'A standard approach that incorrectly handles edge cases.', 'Multiple threads access shared resource unpredictably. Prevent with locks, mutexes, atomic operations, transactions.'], "correct_index": 3},
        {"q": "How do you design a caching strategy?", "difficulty": "Medium", "type": "Technical", "hint": "Correct Answer: Option A. Choose cache-aside vs write-through, define TTL, handle cache invalidation, use Redis/Memcached, monitor hit rate.", "options": ['Choose cache-aside vs write-through, define TTL, handle cache invalidation, use Redis/Memcached, monitor hit rate.', 'Using a deprecated pattern that negatively impacts performance.', 'A standard approach that incorrectly handles edge cases.', 'A completely unrelated method often confused by beginners.'], "correct_index": 0},
        {"q": "Describe a production incident you handled and what you learned.", "difficulty": "Medium", "type": "Behavioral", "hint": "Correct Answer: Option D. STAR: Situation (outage/bug), Actions taken (diagnose, fix, deploy), Result, and retrospective/learnings.", "options": ['A completely unrelated method often confused by beginners.', 'A standard approach that incorrectly handles edge cases.', 'Using a deprecated pattern that negatively impacts performance.', 'STAR: Situation (outage/bug), Actions taken (diagnose, fix, deploy), Result, and retrospective/learnings.'], "correct_index": 3},
        {"q": "What is the N+1 query problem and how do you fix it?", "difficulty": "Medium", "type": "Technical", "hint": "Correct Answer: Option D. 1 query to fetch list + N queries for each item. Fix with eager loading (JOIN), DataLoader, or batch queries.", "options": ['A completely unrelated method often confused by beginners.', 'Using a deprecated pattern that negatively impacts performance.', 'A standard approach that incorrectly handles edge cases.', '1 query to fetch list + N queries for each item. Fix with eager loading (JOIN), DataLoader, or batch queries.'], "correct_index": 3},
        {"q": "Explain microservices vs monolith architecture.", "difficulty": "Medium", "type": "Technical", "hint": "Correct Answer: Option A. Monolith = single deployable. Microservices = independent services. Microservices: more scalable, complex ops.", "options": ['Monolith = single deployable. Microservices = independent services. Microservices: more scalable, complex ops.', 'A completely unrelated method often confused by beginners.', 'A standard approach that incorrectly handles edge cases.', 'Using a deprecated pattern that negatively impacts performance.'], "correct_index": 0},
    ],
    "fullstack_developer": [
        {"q": "How do you handle state management in a large React application?", "difficulty": "Medium", "type": "Technical", "hint": "Correct Answer: Option C. Context API for small apps, Redux/Zustand for complex state, React Query for server state, local state for component-level.", "options": ['A completely unrelated method often confused by beginners.', 'A standard approach that incorrectly handles edge cases.', 'Context API for small apps, Redux/Zustand for complex state, React Query for server state, local state for component-level.', 'Using a deprecated pattern that negatively impacts performance.'], "correct_index": 2},
        {"q": "Explain how HTTP/HTTPS works.", "difficulty": "Easy", "type": "Technical", "hint": "Correct Answer: Option A. HTTP = request/response protocol. HTTPS = HTTP + TLS encryption. TLS handshake establishes secure channel.", "options": ['HTTP = request/response protocol. HTTPS = HTTP + TLS encryption. TLS handshake establishes secure channel.', 'A completely unrelated method often confused by beginners.', 'Using a deprecated pattern that negatively impacts performance.', 'A standard approach that incorrectly handles edge cases.'], "correct_index": 0},
        {"q": "What happens when you type a URL in the browser?", "difficulty": "Medium", "type": "Technical", "hint": "Correct Answer: Option A. DNS lookup → TCP connection → TLS handshake → HTTP request → server processes → response → render.", "options": ['DNS lookup → TCP connection → TLS handshake → HTTP request → server processes → response → render.', 'Using a deprecated pattern that negatively impacts performance.', 'A standard approach that incorrectly handles edge cases.', 'A completely unrelated method often confused by beginners.'], "correct_index": 0},
        {"q": "How do you prevent XSS and CSRF attacks?", "difficulty": "Hard", "type": "Technical", "hint": "Correct Answer: Option D. XSS: sanitize input, CSP headers, escape output. CSRF: CSRF tokens, SameSite cookies, Origin header check.", "options": ['A standard approach that incorrectly handles edge cases.', 'Using a deprecated pattern that negatively impacts performance.', 'A completely unrelated method often confused by beginners.', 'XSS: sanitize input, CSP headers, escape output. CSRF: CSRF tokens, SameSite cookies, Origin header check.'], "correct_index": 3},
        {"q": "What is Server-Side Rendering (SSR) vs Client-Side Rendering (CSR)?", "difficulty": "Medium", "type": "Technical", "hint": "Correct Answer: Option A. SSR: HTML from server, good for SEO, slower TTFB. CSR: HTML in browser, fast after load, poor initial SEO.", "options": ['SSR: HTML from server, good for SEO, slower TTFB. CSR: HTML in browser, fast after load, poor initial SEO.', 'A standard approach that incorrectly handles edge cases.', 'Using a deprecated pattern that negatively impacts performance.', 'A completely unrelated method often confused by beginners.'], "correct_index": 0},
        {"q": "How would you optimize a slow web page?", "difficulty": "Medium", "type": "Technical", "hint": "Correct Answer: Option B. Lighthouse audit → lazy loading, image optimization, code splitting, CDN, minification, server-side caching.", "options": ['A standard approach that incorrectly handles edge cases.', 'Lighthouse audit → lazy loading, image optimization, code splitting, CDN, minification, server-side caching.', 'A completely unrelated method often confused by beginners.', 'Using a deprecated pattern that negatively impacts performance.'], "correct_index": 1},
        {"q": "Explain JWT authentication flow.", "difficulty": "Medium", "type": "Technical", "hint": "Correct Answer: Option C. Login → server signs JWT (header.payload.signature) → client stores → sends in Authorization header → server verifies.", "options": ['Using a deprecated pattern that negatively impacts performance.', 'A completely unrelated method often confused by beginners.', 'Login → server signs JWT (header.payload.signature) → client stores → sends in Authorization header → server verifies.', 'A standard approach that incorrectly handles edge cases.'], "correct_index": 2},
        {"q": "Describe the most complex full-stack project you've built.", "difficulty": "Medium", "type": "Behavioral", "hint": "Correct Answer: Option C. STAR. Mention architecture decisions, challenges (scaling, auth, data), tech stack choices and trade-offs.", "options": ['Using a deprecated pattern that negatively impacts performance.', 'A standard approach that incorrectly handles edge cases.', 'STAR. Mention architecture decisions, challenges (scaling, auth, data), tech stack choices and trade-offs.', 'A completely unrelated method often confused by beginners.'], "correct_index": 2},
        {"q": "What is WebSocket and when would you use it over REST?", "difficulty": "Medium", "type": "Technical", "hint": "Correct Answer: Option B. Persistent bidirectional connection. Use for real-time: chat, live dashboards, gaming, collaborative editing.", "options": ['A completely unrelated method often confused by beginners.', 'Persistent bidirectional connection. Use for real-time: chat, live dashboards, gaming, collaborative editing.', 'A standard approach that incorrectly handles edge cases.', 'Using a deprecated pattern that negatively impacts performance.'], "correct_index": 1},
        {"q": "How do you handle errors gracefully in a full-stack app?", "difficulty": "Medium", "type": "Technical", "hint": "Correct Answer: Option B. Frontend: error boundaries, toast notifications. Backend: try/catch, custom error classes, proper HTTP status, logging.", "options": ['A standard approach that incorrectly handles edge cases.', 'Frontend: error boundaries, toast notifications. Backend: try/catch, custom error classes, proper HTTP status, logging.', 'Using a deprecated pattern that negatively impacts performance.', 'A completely unrelated method often confused by beginners.'], "correct_index": 1},
    ],
    "devops_engineer": [
        {"q": "Explain the CI/CD pipeline you would set up for a microservices app.", "difficulty": "Hard", "type": "Technical", "hint": "Correct Answer: Option A. Code → GitHub → CI (build/test) → Docker image → registry → CD (Helm/ArgoCD deploy to K8s) → monitor.", "options": ['Code → GitHub → CI (build/test) → Docker image → registry → CD (Helm/ArgoCD deploy to K8s) → monitor.', 'A completely unrelated method often confused by beginners.', 'Using a deprecated pattern that negatively impacts performance.', 'A standard approach that incorrectly handles edge cases.'], "correct_index": 0},
        {"q": "What is the difference between Docker and a VM?", "difficulty": "Easy", "type": "Technical", "hint": "Correct Answer: Option B. VM = full OS virtualization (heavy). Docker = container shares host kernel (lightweight, fast, portable).", "options": ['A completely unrelated method often confused by beginners.', 'VM = full OS virtualization (heavy). Docker = container shares host kernel (lightweight, fast, portable).', 'A standard approach that incorrectly handles edge cases.', 'Using a deprecated pattern that negatively impacts performance.'], "correct_index": 1},
        {"q": "How does Kubernetes handle service discovery?", "difficulty": "Hard", "type": "Technical", "hint": "Correct Answer: Option B. Services get DNS names. kube-dns resolves within cluster. ClusterIP for internal, LoadBalancer for external.", "options": ['A completely unrelated method often confused by beginners.', 'Services get DNS names. kube-dns resolves within cluster. ClusterIP for internal, LoadBalancer for external.', 'Using a deprecated pattern that negatively impacts performance.', 'A standard approach that incorrectly handles edge cases.'], "correct_index": 1},
        {"q": "Explain Blue-Green deployment strategy.", "difficulty": "Medium", "type": "Technical", "hint": "Correct Answer: Option A. Two identical environments (Blue=live, Green=new). Switch traffic to Green after validation. Easy rollback.", "options": ['Two identical environments (Blue=live, Green=new). Switch traffic to Green after validation. Easy rollback.', 'A completely unrelated method often confused by beginners.', 'Using a deprecated pattern that negatively impacts performance.', 'A standard approach that incorrectly handles edge cases.'], "correct_index": 0},
        {"q": "What is Infrastructure as Code (IaC) and what tools do you use?", "difficulty": "Medium", "type": "Technical", "hint": "Correct Answer: Option C. Define infra in code (Terraform, Ansible, Pulumi). Version controlled, reproducible, automated provisioning.", "options": ['A completely unrelated method often confused by beginners.', 'Using a deprecated pattern that negatively impacts performance.', 'Define infra in code (Terraform, Ansible, Pulumi). Version controlled, reproducible, automated provisioning.', 'A standard approach that incorrectly handles edge cases.'], "correct_index": 2},
        {"q": "How do you monitor a production Kubernetes cluster?", "difficulty": "Hard", "type": "Technical", "hint": "Correct Answer: Option B. Prometheus + Grafana for metrics, ELK for logs, Jaeger for traces, Alertmanager for notifications.", "options": ['Using a deprecated pattern that negatively impacts performance.', 'Prometheus + Grafana for metrics, ELK for logs, Jaeger for traces, Alertmanager for notifications.', 'A standard approach that incorrectly handles edge cases.', 'A completely unrelated method often confused by beginners.'], "correct_index": 1},
        {"q": "What is a Helm chart?", "difficulty": "Medium", "type": "Technical", "hint": "Correct Answer: Option B. Kubernetes package manager. Bundles manifests as templates with values.yaml. Install/upgrade/rollback apps.", "options": ['A completely unrelated method often confused by beginners.', 'Kubernetes package manager. Bundles manifests as templates with values.yaml. Install/upgrade/rollback apps.', 'Using a deprecated pattern that negatively impacts performance.', 'A standard approach that incorrectly handles edge cases.'], "correct_index": 1},
        {"q": "Describe an incident where you had to debug a production outage.", "difficulty": "Medium", "type": "Behavioral", "hint": "Correct Answer: Option D. STAR: What broke, how you diagnosed (logs/metrics), fix applied, post-mortem done, future prevention.", "options": ['A standard approach that incorrectly handles edge cases.', 'Using a deprecated pattern that negatively impacts performance.', 'A completely unrelated method often confused by beginners.', 'STAR: What broke, how you diagnosed (logs/metrics), fix applied, post-mortem done, future prevention.'], "correct_index": 3},
        {"q": "Explain the 12-factor app methodology.", "difficulty": "Medium", "type": "Technical", "hint": "Correct Answer: Option A. Config in env, stateless, port binding, disposability, dev/prod parity, logs as streams, admin processes.", "options": ['Config in env, stateless, port binding, disposability, dev/prod parity, logs as streams, admin processes.', 'A standard approach that incorrectly handles edge cases.', 'A completely unrelated method often confused by beginners.', 'Using a deprecated pattern that negatively impacts performance.'], "correct_index": 0},
        {"q": "What is Terraform state and how do you manage it?", "difficulty": "Medium", "type": "Technical", "hint": "Correct Answer: Option A. State file tracks real infra. Remote state in S3/Azure Blob + state locking (DynamoDB) for team use.", "options": ['State file tracks real infra. Remote state in S3/Azure Blob + state locking (DynamoDB) for team use.', 'Using a deprecated pattern that negatively impacts performance.', 'A completely unrelated method often confused by beginners.', 'A standard approach that incorrectly handles edge cases.'], "correct_index": 0},
    ],
    "default": [
        {"q": "Tell me about yourself and your background.", "difficulty": "Easy", "type": "Behavioral", "hint": "Correct Answer: Option D. 1-2 min elevator pitch: current role/education, key skills, notable projects, career goals. Tailor to role.", "options": ['Using a deprecated pattern that negatively impacts performance.', 'A completely unrelated method often confused by beginners.', 'A standard approach that incorrectly handles edge cases.', '1-2 min elevator pitch: current role/education, key skills, notable projects, career goals. Tailor to role.'], "correct_index": 3},
        {"q": "What is your greatest technical strength?", "difficulty": "Easy", "type": "Behavioral", "hint": "Correct Answer: Option B. Pick one specific skill, give a concrete example of using it successfully. Link to the role's requirements.", "options": ['A completely unrelated method often confused by beginners.', "Pick one specific skill, give a concrete example of using it successfully. Link to the role's requirements.", 'A standard approach that incorrectly handles edge cases.', 'Using a deprecated pattern that negatively impacts performance.'], "correct_index": 1},
        {"q": "Describe a challenging technical problem you solved.", "difficulty": "Medium", "type": "Behavioral", "hint": "Correct Answer: Option A. STAR format. Be specific about the problem, your approach, code/tools used, and measurable outcome.", "options": ['STAR format. Be specific about the problem, your approach, code/tools used, and measurable outcome.', 'A completely unrelated method often confused by beginners.', 'Using a deprecated pattern that negatively impacts performance.', 'A standard approach that incorrectly handles edge cases.'], "correct_index": 0},
        {"q": "How do you stay current with technology trends?", "difficulty": "Easy", "type": "Behavioral", "hint": "Correct Answer: Option C. Mention specific sources: Hacker News, tech blogs, GitHub trending, conferences, courses, side projects.", "options": ['A standard approach that incorrectly handles edge cases.', 'Using a deprecated pattern that negatively impacts performance.', 'Mention specific sources: Hacker News, tech blogs, GitHub trending, conferences, courses, side projects.', 'A completely unrelated method often confused by beginners.'], "correct_index": 2},
        {"q": "Explain a technical concept to a non-technical person.", "difficulty": "Easy", "type": "Behavioral", "hint": "Correct Answer: Option D. Choose an analogy. Demonstrate empathy, clarity, and ability to adapt communication style.", "options": ['A standard approach that incorrectly handles edge cases.', 'Using a deprecated pattern that negatively impacts performance.', 'A completely unrelated method often confused by beginners.', 'Choose an analogy. Demonstrate empathy, clarity, and ability to adapt communication style.'], "correct_index": 3},
        {"q": "Where do you see yourself in 5 years?", "difficulty": "Easy", "type": "Behavioral", "hint": "Correct Answer: Option A. Align with the company and role. Show ambition but be realistic. Mention skill growth, leadership aspirations.", "options": ['Align with the company and role. Show ambition but be realistic. Mention skill growth, leadership aspirations.', 'Using a deprecated pattern that negatively impacts performance.', 'A completely unrelated method often confused by beginners.', 'A standard approach that incorrectly handles edge cases.'], "correct_index": 0},
        {"q": "What is version control and why is it important?", "difficulty": "Easy", "type": "Technical", "hint": "Correct Answer: Option A. System for tracking code changes (Git). Enables collaboration, rollback, branching, code review.", "options": ['System for tracking code changes (Git). Enables collaboration, rollback, branching, code review.', 'A completely unrelated method often confused by beginners.', 'A standard approach that incorrectly handles edge cases.', 'Using a deprecated pattern that negatively impacts performance.'], "correct_index": 0},
        {"q": "How do you approach learning a new technology?", "difficulty": "Easy", "type": "Behavioral", "hint": "Correct Answer: Option C. Official docs → tutorials → small project → read source code → contribute. Show structured, self-directed learning.", "options": ['Using a deprecated pattern that negatively impacts performance.', 'A completely unrelated method often confused by beginners.', 'Official docs → tutorials → small project → read source code → contribute. Show structured, self-directed learning.', 'A standard approach that incorrectly handles edge cases.'], "correct_index": 2},
        {"q": "Why do you want to work at our company?", "difficulty": "Easy", "type": "Behavioral", "hint": "Correct Answer: Option C. Research the company: mission, products, culture, tech stack. Show genuine interest, connect to your goals.", "options": ['A standard approach that incorrectly handles edge cases.', 'A completely unrelated method often confused by beginners.', 'Research the company: mission, products, culture, tech stack. Show genuine interest, connect to your goals.', 'Using a deprecated pattern that negatively impacts performance.'], "correct_index": 2},
        {"q": "What is your weakest skill and how are you improving it?", "difficulty": "Medium", "type": "Behavioral", "hint": "Correct Answer: Option C. Be honest but choose a real weakness you're actively improving. Show self-awareness and growth mindset.", "options": ['A standard approach that incorrectly handles edge cases.', 'Using a deprecated pattern that negatively impacts performance.', "Be honest but choose a real weakness you're actively improving. Show self-awareness and growth mindset.", 'A completely unrelated method often confused by beginners.'], "correct_index": 2},
    ],
}


CACHE_FILE = os.path.join(os.path.dirname(__file__), "data", "cached_mcq.json")

def get_cached_bank() -> Dict[str, List[Dict]]:
    if os.path.exists(CACHE_FILE):
        try:
            with open(CACHE_FILE, "r", encoding="utf-8") as f:
                return json.load(f)
        except:
            return {}
    return {}

def generate_standard_questions(job_title: str, job_id: str, count: int = 10) -> List[Dict]:
    try:
        client = Groq(api_key=GROQ_API_KEY)
        prompt = f"""You are an expert technical interviewer. Generate {count} standard interview questions for a {job_title} role.
These should be fundamental questions that test the core competencies of this specific role.

Each question MUST be a multiple-choice question (MCQ) with 4 choices.
You MUST respond with a valid JSON OBJECT containing a single key "questions" which is an array of objects.
Example output format:
{{
  "questions": [
    {{
      "q": "question text", 
      "options": ["Choice A", "Choice B", "Choice C", "Choice D"],
      "correct_index": 0,
      "difficulty": "Medium", 
      "type": "Technical|Behavioral", 
      "hint": "Correct Answer: Option - Brief explanation"
    }}
  ]
}}
"""
        response = client.chat.completions.create(
            model=MODEL,
            messages=[{"role": "user", "content": prompt}],
            temperature=0.2,
            max_tokens=2000,
            response_format={"type": "json_object"}
        )
        raw = response.choices[0].message.content.strip()
        data = json.loads(raw)
        qs = data.get("questions", [])[:count]
        
        if len(qs) >= count - 4:
            cache = get_cached_bank()
            cache[job_id] = qs
            os.makedirs(os.path.dirname(CACHE_FILE), exist_ok=True)
            with open(CACHE_FILE, "w", encoding="utf-8") as f:
                json.dump(cache, f, indent=2)
        return qs
    except Exception as e:
        print(f"[interview_prep] Cache Groq error for {job_id}: {e}")
        return []

# Map job IDs to their Q&A bank (use default for roles without specific bank)
def get_questions(job_id: str, count: int = 10) -> List[Dict]:
    # 1. Hardcoded Bank
    if job_id in INTERVIEW_BANK and job_id != "default":
        return INTERVIEW_BANK[job_id][:count]
    
    # 2. Local JSON Cache
    cache = get_cached_bank()
    if job_id in cache:
        return cache[job_id][:count]
        
    # 3. Dynamic Generation (JIT)
    job_title = job_id.replace("_", " ").title()
    print(f"Generating JIT standard questions for {job_title}...")
    qs = generate_standard_questions(job_title, job_id, count)
    if qs:
        return qs[:count]
        
    # 4. Fallback
    return INTERVIEW_BANK.get("default", [])[:count]


# ---------------------------------------------------------------------------
# Groq AI — Generate personalized questions
# ---------------------------------------------------------------------------
def generate_ai_questions(
    job_title: str,
    job_id: str,
    extracted_skills: List[str],
    missing_skills: List[str],
    count: int = 5,
) -> List[Dict]:
    """Generate custom interview questions using Groq, tailored to the user's profile."""
    try:
        client = Groq(api_key=GROQ_API_KEY)

        skills_str = ", ".join(extracted_skills[:15]) if extracted_skills else "general software skills"
        missing_str = ", ".join(missing_skills[:8]) if missing_skills else "none"

        prompt = f"""You are an expert technical interviewer at a top tech company. Generate {count} interview questions for a {job_title} role.

The candidate has these skills: {skills_str}
The candidate is missing these skills: {missing_str}

Generate questions that:
1. Test the candidate's existing skills (2 questions)
2. Probe gaps in their missing skills (2 questions)
3. Are behavioral/situational (1 question)

Each question MUST be a multiple-choice question (MCQ) with 4 choices.
You MUST respond with a valid JSON OBJECT containing a single key "questions" which is an array of objects.
Example output format:
{{
  "questions": [
    {{
      "q": "question text", 
      "options": ["Choice A", "Choice B", "Choice C", "Choice D"],
      "correct_index": 0,
      "difficulty": "Easy|Medium|Hard", 
      "type": "Technical|Behavioral", 
      "hint": "Brief explanation of why the answer is correct"
    }}
  ]
}}
"""

        response = client.chat.completions.create(
            model=MODEL,
            messages=[{"role": "user", "content": prompt}],
            temperature=0.7,
            max_tokens=800,
            response_format={"type": "json_object"}
        )

        import json
        raw = response.choices[0].message.content.strip()
        data = json.loads(raw)
        return data.get("questions", [])[:count]

    except Exception as e:
        print(f"[interview_prep] Groq error: {e}")
        return []
