/**
 * questionBank.js
 * ---------------
 * Offline fallback question bank (25+ questions per role).
 * Used when Groq API is unavailable.
 * Fields: q, options[], correct_index, hint, type, difficulty, source
 */

export const QUESTION_BANK = {

  // ── Data Scientist ───────────────────────────────────────────────────────
  'Data Scientist': [
    { q: 'What is the difference between supervised and unsupervised learning?', type: 'Technical', difficulty: 'Easy', options: ['Supervised uses labeled data; unsupervised does not', 'Supervised is faster; unsupervised is more accurate', 'Supervised works only with images; unsupervised works with text', 'No difference — they are the same'], correct_index: 0, hint: 'Supervised learning trains on labeled examples; unsupervised finds patterns in unlabeled data (clustering, dimensionality reduction).' },
    { q: 'What does "overfitting" mean in machine learning?', type: 'Technical', difficulty: 'Easy', options: ['Model fits training data too well but fails on new data', 'Model is too simple to learn patterns', 'Model uses too many features', 'Model has low training accuracy'], correct_index: 0, hint: 'Overfitting occurs when a model memorizes training data including noise, causing poor generalization. Fix with regularization, cross-validation, or more data.' },
    { q: 'Which metric is most appropriate for an imbalanced binary classification problem?', type: 'Technical', difficulty: 'Medium', options: ['Accuracy', 'F1-Score', 'Mean Squared Error', 'R-squared'], correct_index: 1, hint: 'F1-Score balances Precision and Recall, making it more informative than accuracy when classes are imbalanced.' },
    { q: 'What is cross-validation and why is it used?', type: 'Technical', difficulty: 'Medium', options: ['Splitting data into k folds to estimate model performance robustly', 'Validating data types in a dataset', 'Comparing two datasets', 'A technique to visualize decision boundaries'], correct_index: 0, hint: 'Cross-validation (especially k-fold) reduces variance in performance estimates by testing on multiple data subsets.' },
    { q: 'What is regularization in the context of linear models?', type: 'Technical', difficulty: 'Medium', options: ['A penalty term added to loss function to reduce model complexity', 'Normalizing input features', 'Increasing model capacity', 'Removing outliers from training data'], correct_index: 0, hint: 'L1 (Lasso) and L2 (Ridge) regularization penalize large weights, preventing overfitting.' },
    { q: 'Explain the curse of dimensionality.', type: 'Technical', difficulty: 'Hard', options: ['As dimensions increase, data becomes sparse making learning harder', 'Models with more features always perform better', 'Dimensionality reduction always hurts accuracy', 'Neural networks are unaffected by high dimensions'], correct_index: 0, hint: 'In high dimensions, data points become sparse, distances lose meaning, and models need exponentially more data.' },
    { q: 'What is the difference between bagging and boosting?', type: 'Technical', difficulty: 'Hard', options: ['Bagging trains models in parallel on random subsets; boosting trains sequentially correcting errors', 'Bagging uses decision trees; boosting uses linear models', 'Bagging is for regression; boosting is for classification', 'No significant difference'], correct_index: 0, hint: 'Random Forest is bagging; Gradient Boosting / XGBoost is boosting. Both reduce variance/bias differently.' },
    { q: 'What is PCA and when would you use it?', type: 'Technical', difficulty: 'Medium', options: ['Principal Component Analysis — reduces dimensions by finding variance directions', 'A clustering algorithm', 'A method for handling missing values', 'An ensemble method'], correct_index: 0, hint: 'PCA projects data onto orthogonal axes of maximum variance, reducing features while retaining information.' },
    { q: 'How do you handle missing data in a dataset?', type: 'Technical', difficulty: 'Easy', options: ['Imputation (mean/median/mode), drop rows, or model-based methods', 'Always delete rows with missing values', 'Replace with 0', 'Duplicate adjacent rows'], correct_index: 0, hint: 'Strategy depends on missingness mechanism (MCAR/MAR/MNAR) and data volume. MICE or KNN imputation can preserve distributions.' },
    { q: 'Describe your approach to solving a problem you had no prior experience with.', type: 'Behavioral', difficulty: 'Medium', options: ['Research existing solutions, prototype, iterate with feedback', 'Wait for instructions', 'Ask a colleague to solve it', 'Avoid the problem'], correct_index: 0, hint: 'Structure: describe research approach → prototype → test → iterate. Show learning agility.' },
    { q: 'Tell me about a time you communicated complex data findings to a non-technical audience.', type: 'Behavioral', difficulty: 'Medium', options: ['Used visualizations and simplified narratives to convey insights', 'Sent a raw technical report', 'Avoided the meeting', 'Only explained to technical team'], correct_index: 0, hint: 'Use STAR format. Emphasize how you translated technical results into business impact.' },
    { q: 'What is the difference between Type I and Type II errors?', type: 'Technical', difficulty: 'Medium', options: ['Type I = false positive (reject true null); Type II = false negative (miss true effect)', 'Type I = false negative; Type II = false positive', 'Both are the same', 'Type I is always worse'], correct_index: 0, hint: 'Type I (α) = false alarm. Type II (β) = missed detection. The tradeoff depends on context (medical vs spam detection).' },
    { q: 'What is A/B testing and when would you use it?', type: 'Technical', difficulty: 'Easy', options: ['Controlled experiment comparing two variants to measure impact', 'Comparing two ML models offline', 'A data cleaning technique', 'A visualization method'], correct_index: 0, hint: 'A/B tests randomize users to two conditions, applying hypothesis testing to measure statistically significant differences.' },
    { q: 'What is the difference between correlation and causation?', type: 'Technical', difficulty: 'Easy', options: ['Correlation shows relationship; causation shows one directly causes the other', 'They mean the same thing', 'Causation is always provable from data', 'Correlation implies causation'], correct_index: 0, hint: 'Correlation can be spurious. Causation requires controlled experiments or causal inference methods (RDD, IV, DiD).' },
    { q: 'How would you detect and handle outliers in a dataset?', type: 'Technical', difficulty: 'Medium', options: ['Use IQR, Z-score, or visualization; then cap/remove/transform based on context', 'Always remove outliers', 'Never remove outliers', 'Replace with mean'], correct_index: 0, hint: 'Detection: boxplots, IQR, Z-score, Isolation Forest. Action depends on whether outlier is error or valid extreme.' },
  ],

  // ── ML Engineer ───────────────────────────────────────────────────────────
  'ML Engineer': [
    { q: 'What is the difference between batch and online learning?', type: 'Technical', difficulty: 'Medium', options: ['Batch trains on full dataset at once; online updates incrementally with each sample', 'Batch is faster; online is more accurate', 'Online requires more memory', 'No practical difference'], correct_index: 0, hint: 'Online learning (SGD) is useful for streaming data; batch learning is more stable but less adaptive.' },
    { q: 'How do you deploy a machine learning model to production?', type: 'Technical', difficulty: 'Medium', options: ['Serialize model, containerize with Docker, expose via REST API, monitor with logging', 'Upload model file to server', 'Email model weights to engineering team', 'Store in a database'], correct_index: 0, hint: 'Production ML deployment: serialize (pickle/ONNX) → REST API (FastAPI/Flask) → Docker → CI/CD → monitoring (evidently, MLflow).' },
    { q: 'What is model drift and how do you detect it?', type: 'Technical', difficulty: 'Hard', options: ['Degradation of model performance over time due to distribution shift; detect via monitoring metrics', 'Model growing larger over time', 'Overfitting during training', 'Learning rate decay'], correct_index: 0, hint: 'Data drift = input distribution changes. Concept drift = relationship changes. Detect via PSI, KS test, monitoring predictions.' },
    { q: 'What is MLflow and how does it help in ML workflows?', type: 'Technical', difficulty: 'Medium', options: ['An open-source platform for tracking experiments, packaging models, and deployment', 'A cloud computing platform', 'A deep learning framework', 'A dataset management tool'], correct_index: 0, hint: 'MLflow tracks parameters, metrics, artifacts, and models. Enables reproducibility and model registry.' },
    { q: 'Explain the concept of feature stores.', type: 'Technical', difficulty: 'Hard', options: ['Centralized repository for ML features — serving both training and real-time inference consistently', 'A database for images', 'A hyperparameter tuning tool', 'A library for feature engineering'], correct_index: 0, hint: 'Feature stores (Feast, Tecton) solve the training-serving skew problem by providing consistent feature computation.' },
    { q: 'What are the key components of a CI/CD pipeline for ML?', type: 'Technical', difficulty: 'Hard', options: ['Data validation, model training, evaluation, model registry, deployment, monitoring', 'Just code testing and deployment', 'Only model training automation', 'Feature engineering pipeline'], correct_index: 0, hint: 'MLOps pipelines include: data validation → training → evaluation → registry → staging → production → monitoring.' },
    { q: 'How do you handle class imbalance in training?', type: 'Technical', difficulty: 'Medium', options: ['SMOTE, class weights, undersampling, threshold tuning, or ensemble methods', 'Always oversample the minority class', 'Ignore it — models self-correct', 'Remove the majority class'], correct_index: 0, hint: 'Multiple approaches: resampling (SMOTE), cost-sensitive learning (class_weight), threshold optimization for desired precision/recall.' },
    { q: 'What is the difference between latency and throughput in model serving?', type: 'Technical', difficulty: 'Medium', options: ['Latency = time for single request; throughput = requests per second', 'Latency is total compute time; throughput is memory usage', 'They are the same metric', 'Throughput measures accuracy'], correct_index: 0, hint: 'Low latency is critical for real-time serving; high throughput matters for batch processing. Often a tradeoff.' },
    { q: 'Describe a time you had to optimize a slow ML pipeline.', type: 'Behavioral', difficulty: 'Medium', options: ['Profiled bottleneck, applied vectorization/caching/parallelization, measured improvement', 'Rewrote everything from scratch', 'Ignored performance issues', 'Switched to a different tool without profiling'], correct_index: 0, hint: 'Use STAR: identify bottleneck (profiling) → optimize strategically → measure speedup → document.' },
    { q: 'How do you version control ML models and datasets?', type: 'Technical', difficulty: 'Hard', options: ['DVC for data/model versioning + Git for code + MLflow for experiment tracking', 'Git alone is sufficient for everything', 'Store models in spreadsheets', 'No versioning needed for ML'], correct_index: 0, hint: 'DVC tracks large files (data/models) alongside Git code changes. MLflow records all experiment parameters and metrics.' },
    { q: 'What is quantization in the context of deep learning models?', type: 'Technical', difficulty: 'Hard', options: ['Reducing numerical precision (e.g., float32 → int8) to compress and speed up models', 'Adding more layers to a model', 'A data preprocessing technique', 'A type of activation function'], correct_index: 0, hint: 'Quantization reduces model size and inference latency with minimal accuracy loss. Used for edge/mobile deployment.' },
    { q: 'Explain knowledge distillation.', type: 'Technical', difficulty: 'Hard', options: ['Training a smaller student model to mimic a larger teacher model\'s outputs', 'Extracting information from databases', 'A dataset augmentation strategy', 'A model ensemble technique'], correct_index: 0, hint: 'The student learns from the teacher\'s soft probability outputs, capturing generalization beyond hard labels.' },
    { q: 'Describe a time you disagreed with a team decision on a technical approach.', type: 'Behavioral', difficulty: 'Medium', options: ['Presented data-backed alternative, discussed tradeoffs, reached consensus professionally', 'Implemented my own approach without telling the team', 'Agreed without voicing concerns', 'Escalated immediately to management'], correct_index: 0, hint: 'Show technical reasoning + collaborative resolution. Outcome: team benefited from open discussion.' },
    { q: 'What monitoring would you set up for a production ML model?', type: 'Technical', difficulty: 'Hard', options: ['Data drift, prediction drift, model accuracy degradation, latency, error rates, feature statistics', 'Only server CPU/Memory metrics', 'Random sampling of outputs', 'No monitoring needed post-deployment'], correct_index: 0, hint: 'Full ML observability: input data distribution, prediction distribution, performance metrics, infrastructure metrics.' },
    { q: 'What is gradient clipping and when is it used?', type: 'Technical', difficulty: 'Hard', options: ['Capping gradient magnitudes to prevent exploding gradients in RNN/deep networks', 'Removing negative gradients', 'A regularization technique for CNNs', 'A weight initialization method'], correct_index: 0, hint: 'Gradient clipping prevents exploding gradients (common in RNNs/LSTMs) by scaling gradients when they exceed a threshold.' },
  ],

  // ── Frontend Developer ────────────────────────────────────────────────────
  'Frontend Developer': [
    { q: 'What is the difference between var, let, and const in JavaScript?', type: 'Technical', difficulty: 'Easy', options: ['var is function-scoped and hoisted; let/const are block-scoped; const cannot be reassigned', 'They are identical', 'var is the modern syntax', 'const allows reassignment'], correct_index: 0, hint: 'Use const by default, let when reassignment needed, avoid var in modern code due to scoping issues.' },
    { q: 'Explain the Virtual DOM in React.', type: 'Technical', difficulty: 'Medium', options: ['An in-memory representation of the real DOM; React diffs it to minimize actual DOM updates', 'A copy of the HTML file', 'A browser feature', 'A database for component state'], correct_index: 0, hint: 'React creates a virtual DOM, compares it to the previous render (reconciliation), and batches minimal real DOM changes.' },
    { q: 'What is the difference between controlled and uncontrolled components in React?', type: 'Technical', difficulty: 'Medium', options: ['Controlled: form data managed by React state; Uncontrolled: managed by DOM refs', 'Controlled components are faster', 'Uncontrolled components use Redux', 'No practical difference'], correct_index: 0, hint: 'Controlled components give React full control over form values. Uncontrolled use refs to access DOM directly.' },
    { q: 'What is CSS Flexbox and how does it differ from Grid?', type: 'Technical', difficulty: 'Easy', options: ['Flexbox is 1D (row or column); Grid is 2D (rows and columns simultaneously)', 'Grid is older and deprecated', 'Flexbox handles 2D layouts; Grid handles 1D', 'They are identical'], correct_index: 0, hint: 'Use Flexbox for single-axis alignment (nav bars, button groups); use Grid for complex 2D page layouts.' },
    { q: 'What is event delegation in JavaScript?', type: 'Technical', difficulty: 'Medium', options: ['Attaching a single event listener to a parent element to handle events from children', 'Delegating events to the server', 'A React-specific pattern', 'Preventing event bubbling'], correct_index: 0, hint: 'Event delegation uses event bubbling. Instead of binding listeners to every child, listen on the parent and check event.target.' },
    { q: 'Explain how React hooks work. What problem do they solve?', type: 'Technical', difficulty: 'Medium', options: ['Hooks enable state and lifecycle features in functional components, replacing class components', 'Hooks are only for data fetching', 'Hooks replace Redux', 'Hooks work only in class components'], correct_index: 0, hint: 'useState, useEffect, useMemo, useCallback, useRef. Hooks allow functional components to be stateful and handle side effects.' },
    { q: 'What is lazy loading and how do you implement it in React?', type: 'Technical', difficulty: 'Hard', options: ['Deferring loading of components until needed, using React.lazy() and Suspense', 'Loading all components at once', 'A CSS property', 'A Node.js concept'], correct_index: 0, hint: 'React.lazy(() => import("./Component")) + <Suspense fallback={<Spinner/>}> enables code splitting at component level.' },
    { q: 'What is the purpose of useCallback and useMemo?', type: 'Technical', difficulty: 'Hard', options: ['useCallback memoizes functions; useMemo memoizes computed values to prevent unnecessary re-renders', 'Both cache API responses', 'useMemo replaces useState', 'useCallback is an async hook'], correct_index: 0, hint: 'Use useMemo for expensive calculations; useCallback for stable function references passed to child components.' },
    { q: 'Describe a time you improved the performance of a frontend application.', type: 'Behavioral', difficulty: 'Medium', options: ['Profiled with DevTools, identified renders/bundle/network issues, applied targeted fixes', 'Rewrote the app', 'Added more RAM to server', 'Ignored performance'], correct_index: 0, hint: 'STAR: profiling → root cause → code splitting/memoization/lazy loading → before/after metrics.' },
    { q: 'What is TypeScript and what are its key benefits over JavaScript?', type: 'Technical', difficulty: 'Easy', options: ['A typed superset of JS — provides static typing, better IDE support, and earlier error detection', 'A totally different language', 'Slower than JavaScript', 'Only used in backend development'], correct_index: 0, hint: 'TypeScript catches type errors at compile time, improves refactoring safety, and enables better autocomplete.' },
    { q: 'What is CORS and how do you handle it in a frontend application?', type: 'Technical', difficulty: 'Medium', options: ['Cross-Origin Resource Sharing — browser security policy; handled by server headers or proxy', 'A CSS framework', 'A JavaScript design pattern', 'A React feature'], correct_index: 0, hint: 'CORS is enforced by browsers. Fix: configure server with Access-Control-Allow-Origin header or proxy API requests through same origin.' },
    { q: 'What are Web Vitals and why do they matter?', type: 'Technical', difficulty: 'Medium', options: ['Core performance metrics (LCP, FID, CLS) that measure user experience and affect SEO', 'A testing framework', 'Browser compatibility metrics', 'A deployment metric'], correct_index: 0, hint: 'LCP (loading), FID/INP (interactivity), CLS (visual stability). Google uses them as ranking signals.' },
    { q: 'How do you ensure accessibility in web applications?', type: 'Technical', difficulty: 'Medium', options: ['Semantic HTML, ARIA attributes, keyboard navigation, sufficient color contrast, screen reader testing', 'Only use high-contrast colors', 'Add alt text to all images only', 'Accessibility is optional'], correct_index: 0, hint: 'WCAG guidelines: perceivable, operable, understandable, robust. Use semantic elements, ARIA, focus management, and regular audits.' },
    { q: 'Tell me about a challenging project where you worked with a team under tight deadlines.', type: 'Behavioral', difficulty: 'Medium', options: ['Prioritized tasks, communicated blockers early, delivered core features on time', 'Worked alone to avoid coordination overhead', 'Stayed quiet and just coded', 'Asked for deadline extension without data'], correct_index: 0, hint: 'STAR: situation → task → action (communication, prioritization) → result (on-time delivery + lessons learned).' },
    { q: 'What is the difference between localStorage, sessionStorage, and cookies?', type: 'Technical', difficulty: 'Easy', options: ['localStorage persists; sessionStorage clears on tab close; cookies sent with every HTTP request', 'All three are identical', 'Cookies are the most secure', 'sessionStorage is largest storage option'], correct_index: 0, hint: 'localStorage: domain scope; sessionStorage: tab scope; cookies: sent to server, can be HttpOnly/Secure for security.' },
  ],

  // ── Backend Developer ─────────────────────────────────────────────────────
  'Backend Developer': [
    { q: 'What is the difference between REST and GraphQL?', type: 'Technical', difficulty: 'Medium', options: ['REST uses fixed endpoints; GraphQL uses single endpoint where client specifies exact data needed', 'GraphQL is always better', 'REST is deprecated', 'GraphQL only works with JavaScript'], correct_index: 0, hint: 'GraphQL solves REST\'s over-fetching/under-fetching. REST is simpler and widely cached. Pick based on use case.' },
    { q: 'What is a database index and when should you use one?', type: 'Technical', difficulty: 'Medium', options: ['Data structure that speeds read queries at cost of write speed and storage; use on frequently queried columns', 'Default feature applied to all columns', 'A backup of the database', 'Only used for primary keys'], correct_index: 0, hint: 'B-tree indexes speed SELECT WHERE queries. Avoid over-indexing — each index slows inserts/updates.' },
    { q: 'Explain ACID properties in databases.', type: 'Technical', difficulty: 'Hard', options: ['Atomicity, Consistency, Isolation, Durability — guarantees for reliable database transactions', 'A security protocol', 'An SQL query type', 'A NoSQL concept'], correct_index: 0, hint: 'ACID ensures transactions are reliable: all-or-nothing (Atomic), valid state only (Consistent), concurrent safe (Isolated), permanent (Durable).' },
    { q: 'What is caching and how do you implement it in a backend system?', type: 'Technical', difficulty: 'Medium', options: ['Store frequently accessed data in memory (Redis/Memcached) to reduce database load and latency', 'Storing all data in files', 'A type of database', 'Only for client-side use'], correct_index: 0, hint: 'Cache strategies: Cache-Aside, Write-Through, Write-Behind. Use TTL and invalidation to keep cache fresh.' },
    { q: 'What is the N+1 query problem and how do you solve it?', type: 'Technical', difficulty: 'Hard', options: ['Execute 1 query to get N records, then N more to get related data; fix with JOIN or eager loading', 'A problem with N servers', 'An algorithm efficiency issue', 'A security vulnerability'], correct_index: 0, hint: 'N+1 is a common ORM pitfall. Fix with .include()/.eager_load() (Rails), .joinedload() (SQLAlchemy), or GraphQL DataLoader.' },
    { q: 'How do you secure a REST API?', type: 'Technical', difficulty: 'Medium', options: ['JWT auth, HTTPS, rate limiting, input validation, CORS, least privilege access', 'Just use passwords', 'Only HTTPS is needed', 'Security is handled by the frontend'], correct_index: 0, hint: 'Security layers: authentication (JWT/OAuth), authorization (RBAC), transport (HTTPS), input validation, rate limiting, proper error handling.' },
    { q: 'What is the difference between SQL and NoSQL databases?', type: 'Technical', difficulty: 'Easy', options: ['SQL: relational/structured with ACID; NoSQL: flexible schema, horizontally scalable, various models', 'NoSQL is always faster', 'SQL is deprecated', 'They are the same technology'], correct_index: 0, hint: 'SQL excels at complex queries and relationships. NoSQL (MongoDB, Redis, Cassandra) scales horizontally and handles unstructured data.' },
    { q: 'Explain microservices vs monolithic architecture.', type: 'Technical', difficulty: 'Hard', options: ['Monolith is single deployable unit; microservices decompose into independently deployable services', 'Microservices are always better', 'Monoliths cannot scale', 'They perform identically'], correct_index: 0, hint: 'Monoliths are simpler to start; microservices scale independently but add operational complexity (service discovery, distributed tracing).' },
    { q: 'What is database connection pooling?', type: 'Technical', difficulty: 'Medium', options: ['Reusing a pool of database connections to avoid the cost of creating new connections per request', 'Storing queries in memory', 'Replicating the database', 'A backup mechanism'], correct_index: 0, hint: 'Connection pools (PgBouncer, HikariCP) maintain a set of live connections, reducing latency from repeated TCP handshakes.' },
    { q: 'How do you handle errors gracefully in a backend API?', type: 'Technical', difficulty: 'Medium', options: ['Structured error responses, proper HTTP status codes, logging, no stack trace exposure to client', 'Return 200 for all responses', 'Let errors crash the server', 'Only log to console'], correct_index: 0, hint: 'Use global error handlers, consistent error schema {error, message, code}, proper status codes, and structured logging (Winston, Serilog).' },
    { q: 'Tell me about a production outage you were involved in resolving.', type: 'Behavioral', difficulty: 'Hard', options: ['Stayed calm, diagnosed with monitoring tools, applied fix, communicated status, conducted post-mortem', 'Panicked and rebooted servers', 'Waited for someone else to fix it', 'Ignored user reports'], correct_index: 0, hint: 'STAR: incident → diagnosis process → action taken → resolution → what was learned/improved afterward.' },
    { q: 'What is rate limiting and why is it important?', type: 'Technical', difficulty: 'Medium', options: ['Restricting API requests per client per time window to prevent abuse and protect server resources', 'Limiting server CPU usage', 'A database optimization', 'A load balancing strategy'], correct_index: 0, hint: 'Rate limiting (token bucket, sliding window, fixed window) prevents DoS attacks, ensures fair usage, and controls costs.' },
    { q: 'How do you design a URL shortening service (like bit.ly)?', type: 'Technical', difficulty: 'Hard', options: ['Hash long URL to short key, store mapping in DB/cache, handle redirects, scale with CDN', 'Store full URL in URL bar', 'Use cookies only', 'Generate random numbers'], correct_index: 0, hint: 'Key decisions: hash function (Base62), collision handling, read-heavy caching (Redis), analytics tracking, expiry.' },
    { q: 'Describe how you prioritize multiple urgent tasks simultaneously.', type: 'Behavioral', difficulty: 'Medium', options: ['Assess impact and urgency, communicate with stakeholders, tackle highest priority first, update status', 'Work on all simultaneously', 'Pick randomly', 'Ask manager for every decision'], correct_index: 0, hint: 'Use Eisenhower matrix or ICE scoring. Communicate tradeoffs clearly. Avoid context-switching trap.' },
    { q: 'What is a message queue and when would you use one?', type: 'Technical', difficulty: 'Hard', options: ['Async communication buffer between services (RabbitMQ/Kafka) for decoupling and load buffering', 'A type of database', 'A caching layer', 'A REST endpoint'], correct_index: 0, hint: 'Message queues decouple producers/consumers, enable retry logic, smooth traffic spikes, and enable event-driven architectures.' },
  ],

  // ── Data Analyst ─────────────────────────────────────────────────────────
  'Data Analyst': [
    { q: 'What is the difference between INNER JOIN and LEFT JOIN in SQL?', type: 'Technical', difficulty: 'Easy', options: ['INNER returns only matching rows; LEFT returns all left rows + matched right (NULL if no match)', 'INNER is faster always', 'LEFT JOIN returns only right table rows', 'No difference'], correct_index: 0, hint: 'Use INNER JOIN when you only want matches. LEFT JOIN when you need all records from the primary table.' },
    { q: 'How do you handle NULL values in SQL?', type: 'Technical', difficulty: 'Easy', options: ['Use IS NULL / IS NOT NULL; COALESCE() to replace; NULLIF() for conditional nulls', 'NULL equals 0', 'NULLs are automatically removed by SQL', 'Use != NULL to filter'], correct_index: 0, hint: 'NULL is not equal to anything — even itself. Always use IS NULL. COALESCE returns first non-null value.' },
    { q: 'What are window functions in SQL and give an example?', type: 'Technical', difficulty: 'Hard', options: ['Perform calculations across rows related to current row without collapsing groups (e.g., RANK() OVER PARTITION BY)', 'Functions that work on timeframes', 'Aggregate functions only', 'Subquery functions'], correct_index: 0, hint: 'ROW_NUMBER(), RANK(), LAG(), LEAD(), SUM() OVER (PARTITION BY ... ORDER BY ...) are key window functions.' },
    { q: 'What is the difference between a KPI and a metric?', type: 'Technical', difficulty: 'Easy', options: ['KPIs are strategic measures tied to business goals; metrics are operational data points that may or may not be critical', 'They are the same', 'Metrics are more important than KPIs', 'KPIs are always financial'], correct_index: 0, hint: 'All KPIs are metrics, but not all metrics are KPIs. KPIs are tied directly to strategic objectives.' },
    { q: 'Explain the concept of data normalization in databases.', type: 'Technical', difficulty: 'Medium', options: ['Organizing tables to reduce redundancy and improve data integrity (1NF, 2NF, 3NF)', 'Scaling numerical values to 0-1 range', 'A ML preprocessing technique', 'Converting data types'], correct_index: 0, hint: 'Database normalization reduces update anomalies. 3NF eliminates transitive dependencies. Denormalization trades redundancy for query speed.' },
    { q: 'How would you approach analyzing a sudden drop in website conversion rate?', type: 'Technical', difficulty: 'Hard', options: ['Segment by time/source/device, check for external events, A/B test rollouts, funnel analysis', 'Immediately restart the server', 'Assume it is a data error', 'Only check marketing budget'], correct_index: 0, hint: 'Structured approach: reproduce the metric → segment to isolate → hypothesize root cause → validate → propose fix.' },
    { q: 'What charts are best for showing trends over time?', type: 'Technical', difficulty: 'Easy', options: ['Line charts for continuous trends; bar charts for discrete time periods', 'Pie charts', 'Scatter plots only', 'Histogram is always best'], correct_index: 0, hint: 'Line charts show continuity and direction. Bar charts emphasize comparison at discrete points. Avoid pie charts for time series.' },
    { q: 'What is the difference between OLAP and OLTP systems?', type: 'Technical', difficulty: 'Medium', options: ['OLTP: transactional real-time operations; OLAP: analytical complex queries on historical data', 'They are the same', 'OLAP is for real-time transactions', 'OLTP is only for reporting'], correct_index: 0, hint: 'OLTP: normalized, high write speed (PostgreSQL). OLAP: denormalized, optimized for reads (Redshift, BigQuery, Snowflake).' },
    { q: 'Describe a time you discovered an insight that changed a business decision.', type: 'Behavioral', difficulty: 'Medium', options: ['Identified trend in data, quantified impact, presented clearly, stakeholders adjusted strategy', 'Kept insight private', 'Mentioned it in passing', 'Assumed someone else would find it'], correct_index: 0, hint: 'STAR: data context → analytical approach → insight discovered → business impact/decision changed. Quantify the impact.' },
    { q: 'What is the purpose of GROUP BY in SQL?', type: 'Technical', difficulty: 'Easy', options: ['Aggregate rows sharing the same value in specified columns (e.g., SUM revenue per region)', 'Sort results alphabetically', 'Filter rows from a table', 'Join two tables'], correct_index: 0, hint: 'GROUP BY + aggregate functions (SUM, COUNT, AVG, MAX, MIN) enable summarization by category.' },
    { q: 'How do you validate the accuracy of your analysis?', type: 'Technical', difficulty: 'Medium', options: ['Cross-check with different data sources, sense-check with domain experts, test assumptions explicitly', 'Assume data is always correct', 'Only review final numbers', 'Submit without review'], correct_index: 0, hint: 'Triangulate: multiple sources, sanity checks (totals add up), compare to benchmarks, peer review. Document assumptions.' },
    { q: 'What is a pivot table and when would you use it?', type: 'Technical', difficulty: 'Easy', options: ['A tool to summarize and cross-tabulate data across multiple dimensions for quick exploration', 'A type of chart', 'A SQL JOIN operation', 'A machine learning model'], correct_index: 0, hint: 'Pivot tables allow you to quickly aggregate and compare data across categories without writing SQL.' },
    { q: 'How do you communicate findings to non-technical stakeholders?', type: 'Behavioral', difficulty: 'Medium', options: ['Focus on business impact, use simple visualizations, avoid jargon, tell a data story', 'Show all technical details', 'Send raw data tables', 'Present only to technical team'], correct_index: 0, hint: 'Lead with the business question, then the insight, then the evidence. Use charts, not tables, for executives.' },
    { q: 'What is the difference between mean, median, and mode?', type: 'Technical', difficulty: 'Easy', options: ['Mean = average; Median = middle value; Mode = most frequent', 'All measure the same thing', 'Mode is most accurate', 'Median is always larger than mean'], correct_index: 0, hint: 'Use median for skewed distributions (incomes). Mean is sensitive to outliers. Mode is useful for categorical data.' },
    { q: 'How would you design a dashboard for a sales team?', type: 'Technical', difficulty: 'Medium', options: ['Identify KPIs, design clear hierarchy, use actionable metrics, minimize noise, enable drill-down', 'Include every available metric', 'Use only tables', 'Apply as many chart types as possible'], correct_index: 0, hint: 'Focus on the 3-5 metrics that drive action. Use visual hierarchy. Allow filtering. Refresh cadence should match decision cycles.' },
  ],
};

/**
 * getFallbackQuestions
 * --------------------
 * Get offline questions for a role matching the given difficulty filter.
 * Falls back to "Software Engineer" questions if role not found.
 */
export function getFallbackQuestions(role = '', difficulty = 'All') {
  // Fuzzy-match role name
  const roleKey = Object.keys(QUESTION_BANK).find(k =>
    role.toLowerCase().includes(k.toLowerCase()) ||
    k.toLowerCase().includes(role.toLowerCase())
  ) || 'Data Scientist';

  const questions = QUESTION_BANK[roleKey] || QUESTION_BANK['Data Scientist'];
  if (difficulty === 'All') return questions;
  return questions.filter(q => q.difficulty === difficulty);
}

/** Get all role names available in bank */
export const BANK_ROLES = Object.keys(QUESTION_BANK);
